services:
  postgres:
    image: postgres:17
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2word
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev --import-realm --features=scripts --spi-script-upload-enabled=true
    ports:
      - "7000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: pass2word
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: account3,admin-fine-grained-authz,scripts
      KC_SPI_SCRIPT_UPLOAD_ENABLED: true
    volumes:
      - ./Keycloak/themes:/opt/keycloak/themes
      - ./Keycloak/keycloak-conf:/opt/keycloak/conf
      - ./Keycloak/realm-export:/opt/keycloak/data/import
      - ./Keycloak/realm-export:/tmp/realm-export
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  go-wonok:
    build:
      context: ./Go-backend
      dockerfile: Dockerfile
    container_name: Go-wonok
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=pass2word
      - DB_NAME=postgres
      - KEYCLOAK_URL=http://keycloak:8080
    volumes:
      - ./go-backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: unless-stopped

  next-wongnok:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    container_name: next-wongnok
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:7000
    volumes:
      - ./nextjs-frontend:/app
      - /app/node_modules
    depends_on:
      - go-wonok
    restart: unless-stopped
 
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf:/etc/nginx/conf.d
      - ./nginx/nginx-html:/usr/share/nginx/html
      - ./nginx/nginx-logs:/var/log/nginx
      - ./nginx/ssl-certs:/etc/ssl/certs
    depends_on:
      - keycloak
      - go-wonok
      - next-wongnok
    restart: unless-stopped