// Code generated by mockery v2.53.4. DO NOT EDIT.

package auth_test

import (
	model "wongnok/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: claims
func (_m *MockIUserService) GetByID(claims model.Claims) (model.User, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetByID(claims interface{}) *MockIUserService_GetByID_Call {
	return &MockIUserService_GetByID_Call{Call: _e.mock.On("GetByID", claims)}
}

func (_c *MockIUserService_GetByID_Call) Run(run func(claims model.Claims)) *MockIUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Claims))
	})
	return _c
}

func (_c *MockIUserService_GetByID_Call) Return(_a0 model.User, _a1 error) *MockIUserService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetByID_Call) RunAndReturn(run func(model.Claims) (model.User, error)) *MockIUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipes provides a mock function with given fields: userID, claims
func (_m *MockIUserService) GetRecipes(userID string, claims model.Claims) (model.FoodRecipes, error) {
	ret := _m.Called(userID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 model.FoodRecipes
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.Claims) (model.FoodRecipes, error)); ok {
		return rf(userID, claims)
	}
	if rf, ok := ret.Get(0).(func(string, model.Claims) model.FoodRecipes); ok {
		r0 = rf(userID, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}

	if rf, ok := ret.Get(1).(func(string, model.Claims) error); ok {
		r1 = rf(userID, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipes'
type MockIUserService_GetRecipes_Call struct {
	*mock.Call
}

// GetRecipes is a helper method to define mock.On call
//   - userID string
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetRecipes(userID interface{}, claims interface{}) *MockIUserService_GetRecipes_Call {
	return &MockIUserService_GetRecipes_Call{Call: _e.mock.On("GetRecipes", userID, claims)}
}

func (_c *MockIUserService_GetRecipes_Call) Run(run func(userID string, claims model.Claims)) *MockIUserService_GetRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.Claims))
	})
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) Return(_a0 model.FoodRecipes, _a1 error) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) RunAndReturn(run func(string, model.Claims) (model.FoodRecipes, error)) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertWithClaims provides a mock function with given fields: claims
func (_m *MockIUserService) UpsertWithClaims(claims model.Claims) (model.User, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithClaims")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_UpsertWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWithClaims'
type MockIUserService_UpsertWithClaims_Call struct {
	*mock.Call
}

// UpsertWithClaims is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) UpsertWithClaims(claims interface{}) *MockIUserService_UpsertWithClaims_Call {
	return &MockIUserService_UpsertWithClaims_Call{Call: _e.mock.On("UpsertWithClaims", claims)}
}

func (_c *MockIUserService_UpsertWithClaims_Call) Run(run func(claims model.Claims)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Claims))
	})
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) Return(_a0 model.User, _a1 error) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) RunAndReturn(run func(model.Claims) (model.User, error)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
